<?php
define('ICECAST_URL','949fm.ca');
define('ICECAST_ADMIN_PORT','443');
define('ICECAST_ADMIN_USERNAME','admin');
define('ICECAST_ADMIN_PASSWORD','hackme');
define('ICECAST_MPEG_MOUNTPOINT','stream');
define('ICECAST_AAC_MOUNTPOINT','RadioWestern');
define('ICECAST_OUTFILE','icecast.txt');
;?>